#!/bin/bash
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/amazon 48x64+48+128 amazon.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/animal 48x64+48+128 animal.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/beholder 48x64+48+128 beholder.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/chaos 48x64+48+128 chaos.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/dark_elf 48x64+48+128 dark_elf.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/demon 48x64+48+128 demon.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/dwarf 48x64+48+128 dwarf.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/elemental 48x64+48+128 elemental.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/elf 48x64+48+128 elf.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/farm_animal 64x64+64+128 farm_animal.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/gargoyle 48x64+48+128 gargoyle.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/giant 48x64+48+128 giant.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/giant_animal 64x64+64+128 giant_animal.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/giant_human 96x128+96+256 giant_human.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/gnome 48x64+48+128 gnome.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/goblin 48x64+48+128 goblin.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/golem 48x64+48+128 golem.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/huge_animal 96x128+96+256 huge_animal.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/huger_animal 144x192+144+384 huger_animal.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/human 48x64+48+128 human.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/hybrid 48x64+48+128 hybrid.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/kobold 48x64+48+128 kobold.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/madaram 48x64+48+128 madaram.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/minotaur 48x64+48+128 minotaur.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/mummy 48x64+48+128 mummy.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/mutant 48x64+48+128 mutant.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/mythical_animal 194x256+194+512 mythical_animal.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/orc 48x64+48+128 orc.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/ratfolk 48x64+48+128 ratfolk.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/small_animal 32x32+32+64 small_animal.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/troll 48x64+48+128 troll.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/undead 48x64+48+128 undead.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/vampire 48x64+48+128 vampire.png
#./createtileset.sh ../../../../data/sprites/monsters/stendhal/holiday 48x64+48+128 holiday.png
#./createtileset.sh ../../../../data/sprites/monsters/pol/ogniki 48x64+48+128 pol_ogniki.png
#./createtileset.sh ../../../../data/sprites/monsters/pol/malze 32x32+32+64 pol_sea_animal.png
#./createtileset.sh ../../../../data/sprites/monsters/pol/zwierzeta 48x64+48+128 pol_zwierzeta.png
